# Generated by Django 5.1 on 2024-08-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mosl', models.CharField(choices=[('MOSL', 'MOSL'), ('DB', 'DB'), ('grd', 'GRD'), ('gvt', 'GVT'), ('master', 'MASTER')], max_length=50)),
                ('server', models.CharField(blank=True, db_column='Server', max_length=50, null=True)),
                ('start_time', models.DateTimeField(blank=True, db_column='StartTime', null=True)),
                ('expiry_date', models.DateTimeField(blank=True, db_column='ExpiryDate', null=True)),
                ('ats', models.BooleanField(db_column='ATS', default=False)),
                ('no_of_foid_logged_in', models.CharField(blank=True, db_column='NoOfFoidLoggedIn', max_length=50, null=True)),
                ('order_fired', models.CharField(blank=True, db_column='OrderFired', max_length=50, null=True)),
                ('trades', models.CharField(blank=True, db_column='Trades', max_length=50, null=True)),
                ('dc_trades', models.CharField(blank=True, db_column='DCTrades', max_length=50, null=True)),
                ('scripts_loaded', models.CharField(blank=True, db_column='ScriptsLoaded', max_length=50, null=True)),
                ('contract_file_date', models.DateField(blank=True, db_column='ContractFileDate', null=True)),
                ('stream_id_file_date', models.DateField(blank=True, db_column='StreamIDFileDate', null=True)),
                ('fcast', models.CharField(blank=True, db_column='Fcast', max_length=100, null=True)),
                ('highest_temperature', models.CharField(blank=True, db_column='HighestTemperature', max_length=50, null=True)),
                ('recovery', models.CharField(blank=True, db_column='Recovery', max_length=50, null=True)),
                ('stream_id1_lastsequence', models.CharField(blank=True, db_column='StreamID1_Lastsequence', max_length=50, null=True)),
                ('stream_id1_livesequence', models.CharField(blank=True, db_column='StreamID1_Livesequence', max_length=50, null=True)),
                ('stream_id2_lastsequence', models.CharField(blank=True, db_column='StreamID2_Lastsequence', max_length=50, null=True)),
                ('stream_id2_livesequence', models.CharField(blank=True, db_column='StreamID2_Livesequence', max_length=50, null=True)),
                ('stream_id3_lastsequence', models.CharField(blank=True, db_column='StreamID3_Lastsequence', max_length=50, null=True)),
                ('stream_id3_livesequence', models.CharField(blank=True, db_column='StreamID3_Livesequence', max_length=50, null=True)),
                ('stream_id4_lastsequence', models.CharField(blank=True, db_column='StreamID4_Lastsequence', max_length=50, null=True)),
                ('stream_id4_livesequence', models.CharField(blank=True, db_column='StreamID4_Livesequence', max_length=50, null=True)),
                ('stream_id5_lastsequence', models.CharField(blank=True, db_column='StreamID5_Lastsequence', max_length=50, null=True)),
                ('stream_id5_livesequence', models.CharField(blank=True, db_column='StreamID5_Livesequence', max_length=50, null=True)),
                ('stream_id6_lastsequence', models.CharField(blank=True, db_column='StreamID6_Lastsequence', max_length=50, null=True)),
                ('stream_id6_livesequence', models.CharField(blank=True, db_column='StreamID6_Livesequence', max_length=50, null=True)),
                ('stream_id7_lastsequence', models.CharField(blank=True, db_column='StreamID7_Lastsequence', max_length=50, null=True)),
                ('stream_id7_livesequence', models.CharField(blank=True, db_column='StreamID7_Livesequence', max_length=50, null=True)),
                ('stream_id8_lastsequence', models.CharField(blank=True, db_column='StreamID8_Lastsequence', max_length=50, null=True)),
                ('stream_id8_livesequence', models.CharField(blank=True, db_column='StreamID8_Livesequence', max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Setup',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='orms',
            options={'verbose_name_plural': 'ORMS'},
        ),
    ]
